name: Deploy Go Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest 
    environment: devs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build Go Binary
      run: |
        GOOS=linux GOARCH=amd64 go build -o app

    - name: Stop old app on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}   # ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pkill app || true
          mkdir -p /home/ec2-user/go-backend

    - name: Copy binary to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}   # ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app"
        target: "/home/ec2-user/go-backend"

    - name: Start Go backend
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}   # ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          chmod +x /home/ec2-user/go-backend/app
          nohup /home/ec2-user/go-backend/app > /home/ec2-user/go-backend/app.log 2>&1 &
